// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20211013200408_New-User")]
    partial class NewUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlnDom.Domain.Models.Customer.CustomerDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateRegister");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdate");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeleteDate");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("UserAdDeletedId")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserAdDeletedId");

                    b.Property<string>("UserAdInsertedId")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserAdInsertedId");

                    b.Property<string>("UserAdUpdatedId")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserAdUpdatedId");

                    b.Property<Guid?>("UserDeletedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserDeletedId");

                    b.Property<Guid>("UserInsertedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserInsertedId");

                    b.Property<Guid?>("UserUpdatedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserUpdatedId");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SlnDom.Domain.Models.User.UserDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateRegister");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdate");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeleteDate");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Password");

                    b.Property<string>("UserAdDeletedId")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserAdDeletedId");

                    b.Property<string>("UserAdInsertedId")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserAdInsertedId");

                    b.Property<string>("UserAdUpdatedId")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserAdUpdatedId");

                    b.Property<Guid?>("UserDeletedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserDeletedId");

                    b.Property<Guid>("UserInsertedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserInsertedId");

                    b.Property<Guid?>("UserUpdatedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserUpdatedId");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
